### PR TITLE
default password in config file

### PR DESCRIPTION
**Pull request by tarun1992**
Fix for issue raised no #88

### CODE REVIEW

**Comment by nielsdejong** [comment]
hi @tarun1992 ,

Thanks for the contribution! I just posted a comment about this one in the thread here:
https://github.com/nielsdejong/neodash/issues/88


I'm thinking to make this config.json field optional, for example:
```
dispatch(setConnectionProperties(config['standaloneProtocol'], config['standaloneHost'], config['standalonePort'], config['standaloneDatabase'], state.application.connection.username, config['standalonePassword'] ? config['standalonePassword'] : state.application.connection.password));
```

This way the application will pick up the hardcoded password if specified in `config.json`, otherwise it will default to `state.application.connection.password` (the latest in the application cache). What do you think?

**Comment by nielsdejong** [comment]
Another thought: we should probably add the same thing for the username here, so that it's in sync.

**Comment by tarun1992** [comment]
That's a very good idea. I really like that.

**Comment by nielsdejong** [comment]
Hi @tarun1992 ,
I've made some small changes to this one to pick up the standaloneUsername and standalonePassword fields only if they are specified in the config.json file. 

The behaviour is now like this:
- If standaloneUsername/standalonePassword are not specified (default behaviour), do the same thing as before. The connection modal is presented to the user with all fields prefilled except the username/password.
- If standaloneUsername/standalonePassword are specified in config.json, pick these up, and automatically make the connection to the database + load the dashboard. The connection screen is skipped in its entirety.

Best,
Niels

**Pull request merged**
