### PR TITLE
Support rendering native and custom types in Data Grid

### PR DESCRIPTION
**Pull request by JipSogeti**
I reworked the way data types are handled in the Data Grid and added support for additional types: `boolean`, `number`, `date` and `datetime`. From the screenshot you can't really tell, but before all types were treated as strings. Which isn't great for filtering and sorting. Now you can filter properly with e.g. numeric comparison or filter cells before/after a certain date. In addition to that, `object` cells are now filterable. An `object` is transformed to a `string` with `JSON.stringify()`. But instead of doing that inside the `renderCell` function, I'm doing it with `valueGetter`, which happens before rendering and the output is used by the filtering and sorting functions. So you can now filter all objects containing the string `key` (which is all of them in this example xD).

Schermafbeelding 2022-01-04 om 17 51 40

You can try it out with this example cypher query using the fincen dataset.

```
MATCH Path=(e:Entity)-[:COUNTRY]->(c:Country), (f:Filing)-[r:BENEFITS]->(e)
RETURN e as Node, r as Relationship, Path, e.name as Entity, 10000000000000 as Number, false as Boolean, "https://example.com" as URL, datetime() as DateTime, date() as Date, nodes(Path) as Array, { key: "value" } as Object
LIMIT 20
```

I think this somewhat more modular approach will also make it easier to add additional types in the future.

### CODE REVIEW

**Comment by nielsdejong** [comment]
Hi Jip,
Nice! Agree, I like this modular approach way better than what I had initially built.

I am getting a strange error though when trying to view the table on Firefox. My entire page is frozen, and these two errors pop-up in my browser console:
```
downloadable font: kern: Too large subtable (font-family: "Open Sans" style:normal weight:600 stretch:100 src index:1) source: moz-extension://20124d89-508f-49b1-b24e-71e9d41fd1bf/fonts/opensans/Semibold/OpenSans-Semibold.woff2?v=1.1.0
downloadable font: Table discarded (font-family: "Open Sans" style:normal weight:600 stretch:100 src index:1) source: moz-extension://20124d89-508f-49b1-b24e-71e9d41fd1bf/fonts/opensans/Semibold/OpenSans-Semibold.woff2?v=1.1.0
```
I am using the fincen dataset, with a single report that has your example query, on firefox 95.0.1.
Any idea what might cause this? I see that in Chrome it's working fine, so I imagine Edge would work too.

**Comment by JipSogeti** [comment]
Yes it works fine in Edge too.
I just tried with Firefox 95.0.2 (64-bits) and it works fine for me on MacOS.
The error looks like it is not related to anything I changed in this pull request...
But strange that your page is frozen when trying the example table!
No such issues with http://neodash.graphapp.io/ on that Firefox version?

**Comment by nielsdejong** [comment]
Oh yeah, you're right! it's only happening for me when using firefox, also on the neodash.graphapp.io version.
(9x3 size and 12x3 size reports). The table wiggles a little and then the page freezes. I'll look into this seperately thanks.

**Comment by nielsdejong** [comment]
Did some further experiments with the new implementation of the table.
Discovered a couple of things that break the new record type dectection, mainly when handling arrays:

```
// This breaks the table report now, seemed to work before
RETURN [1,2]
```

```
// Same here
RETURN [true,false]
```

```
// This works, but somehow messes up the layout (I think this was there before)
MATCH p=()-->()
WITH p LIMIT 2
RETURN collect(p)
```

```
// This used to work, but now shows [object, object]
RETURN [{a:1},{b:2}]
```

```
// This crashes the entire application. I don't think spatial properties worked before, but the crash is new
MATCH (c:Country)
RETURN c.point
```

Perhaps you know what's going wrong here?
(P.S. I've just pushed an update to `develop` that fixes the crash issue on Firefox (by upgrading to the latest version of MUI datagrid)

**Comment by JipSogeti** [comment]
Interesting! Will have a look. Thanks for testing.

When working on this I also came across another crash. If you like you can try on http://neodash.graphapp.io/ with this dashboard:
```
{
  "title": "Infinite loop crash?",
  "version": "2.0",
  "settings": {
    "pagenumber": 1,
    "editable": true,
    "parameters": {
      "neodash_entity_name": null,
      "neodash_country_name": null
    }
  },
  "pages": [
    {
      "title": "Crash",
      "reports": [
        {
          "title": "Infinite loop?",
          "query": "MATCH Path=(e:Entity)-[r:COUNTRY]->(c:Country), (f:Filing)-[:BENEFITS]->(e)\nRETURN e as Node, r as Relationship, Path, e.name as Entity, c.name as Country, suM(f.amount) as `Total Benefit ($)`\nLIMIT 20",
          "width": "12",
          "type": "table",
          "height": "3",
          "selection": {},
          "settings": {}
        }
      ]
    },
    {
      "title": "Safe",
      "reports": []
    }
  ]
}
```

Click the "Crash" tab to make the whole grid wiggle and finally lock up the page. Seems there's an infinite loop when rendering the Path column.

**Comment by nielsdejong** [comment]
Hi Jip, tried that just now - no issues for me there strangely.
Likely the wiggle is the same issue I patched this morning- is it the same as the thing I recorded here? (https://drive.google.com/file/d/1Kg1H9wAji1aNbvGxWkGWvDmLEpNV-8tB/view?usp=sharing)

**Comment by JipSogeti** [comment]
Interesting, quite sure it should happen for you too. It looks the same as in your video. But I can still create the infinite loop on the latest dev branch so doesn't seem related to the mui grid version.

https://user-images.githubusercontent.com/94383160/148236609-fb92afdf-86e0-4eff-aae5-30d2cf8a7ff2.mp4

I've added a log statement before this line to show there's an infinite loop:
https://github.com/nielsdejong/neodash/blob/23b37e425ecc0468a1110d6ec885049afd9b3626/src/chart/TableChart.tsx#L42

**Comment by JipSogeti** [comment]
Looking into the infinite loop some more, can reproduce it with this dashboard on both Chrome and Edge:

```json
{
  "title": "Infinite loop crash?",
  "version": "2.0",
  "settings": {
    "pagenumber": 1,
    "editable": true,
    "parameters": {}
  },
  "pages": [
    {
      "title": "Crash",
      "reports": [
        {
          "title": "Infinite loop?",
          "query": "MATCH (n)\nRETURN 'a' as a, 'b' as b, 'c' as c, 'd' as d, 'e' as e, 'f' as f\nLIMIT 6",
          "width": "12",
          "type": "table",
          "height": "3",
          "selection": {},
          "settings": {}
        }
      ]
    },
    {
      "title": "Safe",
      "reports": []
    }
  ]
}
```

It doesn't happen when I use LIMIT 3. So seems like there should at least be pagination. And best of all, it's window size dependent xD For me it happens from 1662px wide.

**Comment by JipSogeti** [comment]
Sorry! My bad! Was testing the wrong version. You fixed the infinite loop by upgrading the MUI datagrid.

**Comment by nielsdejong** [comment]
Great! Merging this

**Pull request merged**
