### PR TITLE
Apply global parameter value to selection chart

### PR DESCRIPTION
**Pull request by JipSogeti**
All other charts apply the current global parameter value in their Cypher queries. To keep consistent also apply the state to the parameter selection chart. Previously the value for the Parameter Selection chart would be empty when loading the dashboard.

https://user-images.githubusercontent.com/94383160/146373514-978520e2-7fa2-442e-991f-fdbd6882da02.mp4

### CODE REVIEW

**Comment by nielsdejong** [comment]
Hey Jip,
Looks good! I added some small fixes to ensure that the code checks work nicely (on the charts interface).
Have also reorganized some of the lines on the Parameter Select chart to avoid the case where some of the vars may be uninitialized. If you think it's all good, let me know and I'll merge it in to develop.

Cheers
Niels

**Comment by JipSogeti** [comment]
Hi Niels. I think you introduced a bug, which I tried to workaround with the strange order of variables (and checking `query ` twice). Switching to a different report tab, and back to the one with parameter selection chart will result in a white screen...

Happend to me too when I was working on this. Returning early seems to be the cause: https://github.com/nielsdejong/neodash/pull/47/commits/9be84545ac186da46382a6de3f2943a4a0c98837#diff-473c1d1ce3cd01f11a956c36a6936065e9d2f2a716212aac9e5e18a05775d9ecR25

**Comment by JipSogeti** [comment]
I can reproduce the 'white page' error again with the current code.

```
Warning: React has detected a change in the order of Hooks called by NeoParameterSelectionChart. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useEffect                  useEffect
2. undefined                  useState
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in NeoParameterSelectionChart (created by NeoReport)
    in div (created by NeoReport)
    in NeoReport (created by NeoCardView)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (created by NeoCardView)
    in div (created by styled.div)
    in styled.div (created by NeoCardView)
    in div (created by NeoCardView)
    in NeoCardView (created by NeoCard)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (created by NeoCard)
    in div (created by Transition)
    in div (created by Transition)
    in div (created by Transition)
    in Transition (created by ForwardRef(Collapse))
    in ForwardRef(Collapse) (created by WithStyles(ForwardRef(Collapse)))
    in WithStyles(ForwardRef(Collapse)) (created by NeoCard)
    in div (created by NeoCard)
    in NeoCard (created by Connect(NeoCard))
    in Connect(NeoCard) (created by NeoPage)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by NeoPage)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by NeoPage)
    in div (created by NeoPage)
    in NeoPage (created by Connect(NeoPage))
    in Connect(NeoPage) (created by Dashboard)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (created by Dashboard)
    in main (created by Dashboard)
    in Component (created by Dashboard)
    in Dashboard (created by Connect(Dashboard))
    in Connect(Dashboard) (created by Application)
    in div (created by Application)
    in Application (created by Connect(Application))
    in Connect(Application) (created by HotExportedConnect(Application))
    in AppContainer (created by HotExportedConnect(Application))
    in HotExportedConnect(Application)
    in PersistGate
    in Provider
    in StrictMode
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
warnOnHookMismatchInDev @ react-dom.development.js:14715
updateHookTypesDev @ react-dom.development.js:14674
useState @ react-dom.development.js:15944
useState @ react.development.js:1508
NeoParameterSelectionChart @ ParameterSelectionChart.tsx:46
ProxyFacade @ react-hot-loader.development.js:830
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
beginWork$1 @ react-dom.development.js:23179
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:14980 
        
       Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom.development.js:14980)
    at updateReducer (react-dom.development.js:15038)
    at updateState (react-dom.development.js:15237)
    at Object.useState (react-dom.development.js:15949)
    at Object.useState (react.development.js:1508)
    at NeoParameterSelectionChart (ParameterSelectionChart.tsx:46)
    at ProxyFacade (react-hot-loader.development.js:830)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
updateWorkInProgressHook @ react-dom.development.js:14980
updateReducer @ react-dom.development.js:15038
updateState @ react-dom.development.js:15237
useState @ react-dom.development.js:15949
useState @ react.development.js:1508
NeoParameterSelectionChart @ ParameterSelectionChart.tsx:46
ProxyFacade @ react-hot-loader.development.js:830
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:19527 
        
       The above error occurred in the <NeoParameterSelectionChart> component:
    in NeoParameterSelectionChart (created by NeoReport)
    in div (created by NeoReport)
    in NeoReport (created by NeoCardView)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (created by NeoCardView)
    in div (created by styled.div)
    in styled.div (created by NeoCardView)
    in div (created by NeoCardView)
    in NeoCardView (created by NeoCard)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (created by NeoCard)
    in div (created by Transition)
    in div (created by Transition)
    in div (created by Transition)
    in Transition (created by ForwardRef(Collapse))
    in ForwardRef(Collapse) (created by WithStyles(ForwardRef(Collapse)))
    in WithStyles(ForwardRef(Collapse)) (created by NeoCard)
    in div (created by NeoCard)
    in NeoCard (created by Connect(NeoCard))
    in Connect(NeoCard) (created by NeoPage)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by NeoPage)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by NeoPage)
    in div (created by NeoPage)
    in NeoPage (created by Connect(NeoPage))
    in Connect(NeoPage) (created by Dashboard)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (created by Dashboard)
    in main (created by Dashboard)
    in Component (created by Dashboard)
    in Dashboard (created by Connect(Dashboard))
    in Connect(Dashboard) (created by Application)
    in div (created by Application)
    in Application (created by Connect(Application))
    in Connect(Application) (created by HotExportedConnect(Application))
    in AppContainer (created by HotExportedConnect(Application))
    in HotExportedConnect(Application)
    in PersistGate
    in Provider
    in StrictMode

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
callback @ react-dom.development.js:20744
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19858
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-hot-loader.development.js:297 
        
       Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom.development.js:14980)
    at updateReducer (react-dom.development.js:15038)
    at updateState (react-dom.development.js:15237)
    at Object.useState (react-dom.development.js:15949)
    at Object.useState (react.development.js:1508)
    at NeoParameterSelectionChart (ParameterSelectionChart.tsx:46)
    at ProxyFacade (react-hot-loader.development.js:830)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
error @ react-hot-loader.development.js:297
componentDidCatch @ react-hot-loader.development.js:2402
callback @ react-dom.development.js:20749
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19858
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-hot-loader.development.js:2409 
        
       Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom.development.js:14980)
    at updateReducer (react-dom.development.js:15038)
    at updateState (react-dom.development.js:15237)
    at Object.useState (react-dom.development.js:15949)
    at Object.useState (react.development.js:1508)
    at NeoParameterSelectionChart (ParameterSelectionChart.tsx:46)
    at ProxyFacade (react-hot-loader.development.js:830)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
updateWorkInProgressHook @ react-dom.development.js:14980
updateReducer @ react-dom.development.js:15038
updateState @ react-dom.development.js:15237
useState @ react-dom.development.js:15949
useState @ react.development.js:1508
NeoParameterSelectionChart @ ParameterSelectionChart.tsx:46
ProxyFacade @ react-hot-loader.development.js:830
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:19527 
        
       The above error occurred in the <AppContainer> component:
    in AppContainer (created by HotExportedConnect(Application))
    in HotExportedConnect(Application)
    in PersistGate
    in Provider
    in StrictMode

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:19527
logError @ react-dom.development.js:19564
update.callback @ react-dom.development.js:20708
callCallback @ react-dom.development.js:12490
commitUpdateQueue @ react-dom.development.js:12511
commitLifeCycles @ react-dom.development.js:19883
commitLayoutEffects @ react-dom.development.js:22803
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
commitRootImpl @ react-dom.development.js:22541
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
commitRoot @ react-dom.development.js:22381
finishSyncRender @ react-dom.development.js:21807
performSyncWorkOnRoot @ react-dom.development.js:21793
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:14980 
        
       Uncaught Error: Rendered more hooks than during the previous render.
    at updateWorkInProgressHook (react-dom.development.js:14980)
    at updateReducer (react-dom.development.js:15038)
    at updateState (react-dom.development.js:15237)
    at Object.useState (react-dom.development.js:15949)
    at Object.useState (react.development.js:1508)
    at NeoParameterSelectionChart (ParameterSelectionChart.tsx:46)
    at ProxyFacade (react-hot-loader.development.js:830)
    at renderWithHooks (react-dom.development.js:14803)
    at updateFunctionComponent (react-dom.development.js:17034)
    at beginWork (react-dom.development.js:18610)
updateWorkInProgressHook @ react-dom.development.js:14980
updateReducer @ react-dom.development.js:15038
updateState @ react-dom.development.js:15237
useState @ react-dom.development.js:15949
useState @ react.development.js:1508
NeoParameterSelectionChart @ ParameterSelectionChart.tsx:46
ProxyFacade @ react-hot-loader.development.js:830
renderWithHooks @ react-dom.development.js:14803
updateFunctionComponent @ react-dom.development.js:17034
beginWork @ react-dom.development.js:18610
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
beginWork$1 @ react-dom.development.js:23203
performUnitOfWork @ react-dom.development.js:22157
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
eval @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
react-dom.development.js:88 
        
       Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in NeoReport (created by NeoCardView)
    in div (created by ForwardRef(CardContent))
    in ForwardRef(CardContent) (created by WithStyles(ForwardRef(CardContent)))
    in WithStyles(ForwardRef(CardContent)) (created by NeoCardView)
    in div (created by styled.div)
    in styled.div (created by NeoCardView)
    in div (created by NeoCardView)
    in NeoCardView (created by NeoCard)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by ForwardRef(Card))
    in ForwardRef(Card) (created by WithStyles(ForwardRef(Card)))
    in WithStyles(ForwardRef(Card)) (created by NeoCard)
    in div (created by Transition)
    in div (created by Transition)
    in div (created by Transition)
    in Transition (created by ForwardRef(Collapse))
    in ForwardRef(Collapse) (created by WithStyles(ForwardRef(Collapse)))
    in WithStyles(ForwardRef(Collapse)) (created by NeoCard)
    in div (created by NeoCard)
    in NeoCard (created by Connect(NeoCard))
    in Connect(NeoCard) (created by NeoPage)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by NeoPage)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by NeoPage)
    in div (created by NeoPage)
    in NeoPage (created by Connect(NeoPage))
    in Connect(NeoPage) (created by Dashboard)
    in div (created by ForwardRef(Container))
    in ForwardRef(Container) (created by WithStyles(ForwardRef(Container)))
    in WithStyles(ForwardRef(Container)) (created by Dashboard)
    in main (created by Dashboard)
    in Component (created by Dashboard)
    in Dashboard (created by Connect(Dashboard))
    in Connect(Dashboard) (created by Application)
    in div (created by Application)
    in Application (created by Connect(Application))
    in Connect(Application) (created by HotExportedConnect(Application))
```

**Comment by JipSogeti** [comment]
I looked at this component some more, and I think it needs a different approach. Currently you fetch new autocomplete options via cypher queries, and you debounce these requests. You only ask for the options which contain the current value, so the autocomplete only suggests the appropriate options.

But do you really need to fetch these options again? I think you can just fetch all the options once, and leave the filtering to the autocomplete component itself. Do you think that's possible?

For example, fill list `options` with all `name` property values from nodes with label `Entity` (only once). Then just pass this list as `options` in the `<Autocomplete/>` component.

```tsx
<Autocomplete
  id="combo-box-demo"
  options={options}
  getOptionLabel={(option) => option.title}
  style={{ width: 300 }}
  renderInput={(params) => <TextField {...params} label="Combo box" variant="outlined" />}
/>
```

**Comment by nielsdejong** [comment]
Hey @JipSogeti ,
DId some more work on this issue this morning, and I've come up with a neat solution (I think):
Everything can still be a constant, as the new of hooks is always the same before the return. 

ParameterSelectionChart.tsx:L32 now sets the value of the input if we notice that the local state is different from the global state as expected (e.g. when a page is switched, or a dashboard is loaded). This does exactly what we need. 

I agree that the Autocomplete single fetch here would be simpler, but that can break for huge databases (both in the report settings and the report view components). See https://github.com/nielsdejong/neodash/issues/50 which was opened yesterday.
Perhaps this prefetch could be an optional setting, but I think we might need to move that discussion into another thread to avoid blocking this fix.

Could you check if my latest fixes work on your side? I've done a bit of testing with different cases locally and for me it all appears to be working nicely at the moment.

Niels

**Comment by JipSogeti** [comment]
Thanks for all the work you put into it 🙂 

I did still find a bug:

https://user-images.githubusercontent.com/94383160/147220421-d5c1154c-5bdd-413c-8e6e-c116fc31297c.mp4

The autocomplete options are still from the previous dashboard.

**Comment by nielsdejong** [comment]
https://github.com/nielsdejong/neodash/pull/47/commits/5ed29e2062fb18670d8bd96a58db85f323f70cf6

This should fix that too, autocomplete suggestions are cleared on page change.

**Comment by JipSogeti** [comment]
Verified the autocomplete suggestions are indeed cleared on page change.

Currently I do need to change the value, otherwise autocomplete suggestions won't show up again.

After switching tabs, the auto complete dropdown will only show: "No options".

Schermafbeelding 2021-12-23 om 17 44 30

After changing the value, options will be shown again:
Schermafbeelding 2021-12-23 om 17 47 41

**Comment by nielsdejong** [comment]
Hi, I looked into that a little, but wasn't able to come up with an easy fix. I'm gonna go ahead and merge this and look into that issue later.

Thanks for all the help!

**Pull request merged**
